---
title: Shaila Jinnat (Runi)
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
url: https://runijinnat.github.oi
baseurl: "/"
email: runibottola@gmail.com
description: This is a portfolio site of mine. My projects and experiments are shown
  here
social:
- title: twitter
  url: "#"
- title: facebook
  url: "#"
- title: stack-overflow
  url: "#"
- title: bitbucket
  url: "#"
- title: github
  url: "#"
address:
- line: House-126, Road-19 (Bankers lane), Nirala R/A
- line: Khulna, Bangladesh
markdown: kramdown
permalink: pretty
