---
title: Shaila Jinnat (Runi)
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: runibottola@gmail.com
description: ''
baseurl: ''
url: ''
twitter_username: 
github_username: 
markdown: kramdown
