---
title: CodeLab
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
url: https://portfolio.utsargo.me
baseurl: https://portfolio.utsargo.me
email: royutsargo@gmail.com
description: This is a portfolio site of mine. My projects and experiments are shown
  here
social:
- title: twitter
  url: "#"
- title: facebook
  url: https://web.facebook.com/utsargo.roy
- title: stack-overflow
  url: "#"
- title: bitbucket
  url: http://bitbucket.org/utsargo
- title: github
  url: http://github.com/utsargo
address:
- line: Pujakhola, Boyra
- line: Kulna 9000
markdown: kramdown
permalink: pretty
